const D=window.FILO_DATA;
const P=Object.keys(D.players);
const app=document.getElementById('app');
let tab='home';
const pct=x=>x==null?'—':(x*100).toFixed(1)+'%';
const n=(x,d=2)=>Number(x??0).toFixed(d);
const perGame=(x,k)=>x.gp?x[k]/x.gp:0;
const statLabel={pts:'Points',reb:'Rebounds',ast:'Assists',stl:'Steals',blk:'Blocks',tpm:'3PM'};
function rank(k){return [...P].sort((a,b)=>(D.players[b][k]??0)-(D.players[a][k]??0))}
function rankBy(fn){return [...P].sort((a,b)=>fn(D.players[b])-fn(D.players[a]))}
function rows(ps){return `<div class="tbl"><table><thead><tr><th>Player</th><th>GP</th><th>W%</th><th>PTS</th><th>PPG</th><th>FG%</th><th>3P%</th><th>RPG</th><th>APG</th><th>SPG</th><th>BPG</th><th>TOPG</th><th>PPS</th></tr></thead><tbody>${ps.map(p=>{const x=D.players[p];return `<tr><td><span class="pl" data-profile="${p}">${p}</span></td><td>${x.gp}</td><td>${pct(x.wins/x.gp)}</td><td>${x.pts}</td><td>${n(x.ppg)}</td><td>${pct(x.fg_pct)}</td><td>${pct(x.tp_pct)}</td><td>${n(x.rpg)}</td><td>${n(x.apg)}</td><td>${n(perGame(x,'stl'))}</td><td>${n(perGame(x,'blk'))}</td><td>${n(perGame(x,'tov'))}</td><td>${n(x.pps,3)}</td></tr>`}).join('')}</tbody></table></div>`}
function featureCard(title,copy,target){return `<div class="card click" data-tabjump="${target}"><div class="kicker">Interactive</div><div class="pn">${title}</div><p>${copy}</p></div>`}
function home(){const s=rank('pts')[0],r=rank('reb')[0],a=rank('ast')[0],w=rankBy(x=>x.wins/x.gp)[0];return `<section class="hero"><div class="eye">Stats through Run ${D.through_run}</div><h1>Pickup basketball,<br>treated like a league.</h1><p>Career stats, scouting, comparisons, lineup tools and run history for the Filo Lakers.</p></section><div class="grid g4"><div class="card"><div class="big">${s}</div><div class="lab">Scoring leader · ${D.players[s].pts}</div></div><div class="card"><div class="big">${r}</div><div class="lab">Rebound leader · ${D.players[r].reb}</div></div><div class="card"><div class="big">${a}</div><div class="lab">Assist leader · ${D.players[a].ast}</div></div><div class="card"><div class="big">${w}</div><div class="lab">Win% leader · ${pct(D.players[w].wins/D.players[w].gp)}</div></div></div><div class="sec"><div><h2>Current leaderboard</h2><p>Official career totals.</p></div></div>${rows(rank('pts').slice(0,8))}<div class="sec"><div><h2>Latest run</h2><p>Most recent recorded session.</p></div></div>${runCard(D.runs.at(-1),true)}<div class="sec"><div><h2>Explore the league</h2></div></div><div class="grid g3">${featureCard('Compare players','Head-to-head statistical comparison.','compare')}${featureCard('Chemistry Lab','Role-fit analysis without inventing lineup records.','chemistry')}${featureCard('Lineup Lab','Build a five and inspect balance, strengths and gaps.','lineup')}</div>`}
function leaders(){return `<section class="hero"><div class="eye">All-time</div><h1>Leaderboards</h1><p>Official career totals and per-game rates through Run ${D.through_run}.</p></section>${rows(rank('pts'))}`}
function playerCard(p){const x=D.players[p],m=D.meta[p];return `<div class="card click" data-profile="${p}"><div class="pn">${p}</div><div class="role">${m.role}</div><p>${m.position}</p><div class="mini"><div><b>${n(x.ppg)}</b><span>PPG</span></div><div><b>${n(x.rpg)}</b><span>RPG</span></div><div><b>${pct(x.tp_pct)}</b><span>3P%</span></div><div><b>${pct(x.wins/x.gp)}</b><span>WIN%</span></div></div><div class="tags">${m.traits.slice(0,3).map(t=>`<span class="tag">${t}</span>`).join('')}</div></div>`}
function players(){return `<section class="hero"><div class="eye">Scouting index</div><h1>Players</h1><p>Statistical profiles plus the basketball context behind each role.</p></section><div class="grid g3">${P.map(playerCard).join('')}</div>`}
function playerRunHighlights(p){const hits=D.runs.filter(r=>Object.values(r.leaders).some(v=>v.player===p));if(!hits.length)return `<div class="empty">No run-leading category recorded yet.</div>`;return `<div class="run-grid">${hits.map(r=>runCard(r,false,p)).join('')}</div>`}
function profile(p){const x=D.players[p],m=D.meta[p];const rankings={scoring:rankBy(y=>y.ppg).indexOf(p)+1,rebounding:rankBy(y=>y.rpg).indexOf(p)+1,playmaking:rankBy(y=>y.apg).indexOf(p)+1,winning:rankBy(y=>y.wins/y.gp).indexOf(p)+1};app.innerHTML=`<section class="hero profile-banner"><div><div class="eye">${m.position}</div><h1>${p}</h1><div class="role">${m.role}</div><p>${m.blurb}</p><p>NBA playstyle comp: <b>${m.comp}</b></p><div class="tags">${m.traits.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><div class="profile-score"><div class="big">${pct(x.wins/x.gp)}</div><div class="lab">Career win rate</div></div></section><div class="grid g4"><div class="card"><div class="big">${n(x.ppg)}</div><div class="lab">PPG · #${rankings.scoring}</div></div><div class="card"><div class="big">${n(x.rpg)}</div><div class="lab">RPG · #${rankings.rebounding}</div></div><div class="card"><div class="big">${n(x.apg)}</div><div class="lab">APG · #${rankings.playmaking}</div></div><div class="card"><div class="big">${n(x.pps,3)}</div><div class="lab">Points per shot</div></div></div><div class="sec"><div><h2>Career line</h2><p>Official statistics.</p></div></div>${rows([p])}<div class="sec"><div><h2>Scouting profile</h2><p>Role context tracked alongside the box score.</p></div></div><div class="grid g2"><div class="card"><h3>What the role says</h3><p>${m.blurb}</p><div class="tags">${m.traits.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><div class="card"><h3>League standing</h3><div class="metric-row"><span class="label">Scoring rate</span><span></span><span class="value">#${rankings.scoring}</span></div><div class="metric-row"><span class="label">Rebounding rate</span><span></span><span class="value">#${rankings.rebounding}</span></div><div class="metric-row"><span class="label">Playmaking rate</span><span></span><span class="value">#${rankings.playmaking}</span></div><div class="metric-row"><span class="label">Win rate</span><span></span><span class="value">#${rankings.winning}</span></div></div></div>${p==='Ljah'?'<div class="note" style="margin-top:16px"><b>Context note:</b> Runs 2 and 7 were injury-affected. Official stats remain included; contextual analysis should also consider a view excluding those runs.</div>':''}${p==='David'?'<div class="note" style="margin-top:16px"><b>Context note:</b> Run 9 was a return-from-injury run and is known to be less representative.</div>':''}<div class="sec"><div><h2>Recorded run highlights</h2><p>Runs where ${p} led at least one tracked category.</p></div></div>${playerRunHighlights(p)}`;bind();scrollTo(0,0)}
function compare(){const options=P.map(p=>`<option value="${p}">${p}</option>`).join('');return `<section class="hero"><div class="eye">Head to head</div><h1>Player Compare</h1><p>Compare production, efficiency and team success side by side.</p></section><div class="card"><div class="compare-head"><select id="cmpA">${options}</select><div class="vs">VS</div><select id="cmpB">${options}</select></div><div id="comparison" style="margin-top:18px"></div></div>`}
function renderComparison(){const a=document.getElementById('cmpA'),b=document.getElementById('cmpB');if(!a||!b)return;if(a.value===b.value)b.value=P.find(x=>x!==a.value)||a.value;const A=D.players[a.value],B=D.players[b.value];const metrics=[['PPG',A.ppg,B.ppg,2],['RPG',A.rpg,B.rpg,2],['APG',A.apg,B.apg,2],['SPG',perGame(A,'stl'),perGame(B,'stl'),2],['BPG',perGame(A,'blk'),perGame(B,'blk'),2],['FG%',A.fg_pct,B.fg_pct,'pct'],['3P%',A.tp_pct,B.tp_pct,'pct'],['PPS',A.pps,B.pps,3],['Win%',A.wins/A.gp,B.wins/B.gp,'pct']];document.getElementById('comparison').innerHTML=`<div class="grid g2"><div><div class="pn">${a.value}</div><div class="role">${D.meta[a.value].role}</div></div><div style="text-align:right"><div class="pn">${b.value}</div><div class="role">${D.meta[b.value].role}</div></div></div><div style="margin-top:14px">${metrics.map(([label,av,bv,fmt])=>{const af=fmt==='pct'?pct(av):n(av,fmt),bf=fmt==='pct'?pct(bv):n(bv,fmt);return `<div class="metric-row"><span class="label">${label}</span><span class="value ${av>bv?'winner':''}">${af}</span><span class="value ${bv>av?'winner':''}">${bf}</span></div>`}).join('')}</div>`}
function chemistry(){const options=P.map(p=>`<option value="${p}">${p}</option>`).join('');return `<section class="hero"><div class="eye">Role fit</div><h1>Chemistry Lab</h1><p>Compare two player archetypes and see where their strengths complement or overlap. This is a role-fit tool, not a fabricated historical win-rate model.</p></section><div class="note"><b>Historical chemistry records are not shown yet.</b> The current repo does not contain game-by-game lineup assignments. When that data is added, this page can calculate real duo, trio and five-man records.</div><div class="card" style="margin-top:14px"><div class="compare-head"><select id="chemA">${options}</select><div class="vs">+</div><select id="chemB">${options}</select></div><div id="chemResult" style="margin-top:18px"></div></div>`}
function renderChemistry(){const a=document.getElementById('chemA'),b=document.getElementById('chemB');if(!a||!b)return;if(a.value===b.value)b.value=P.find(x=>x!==a.value)||a.value;const ma=D.meta[a.value],mb=D.meta[b.value];const shared=ma.traits.filter(t=>mb.traits.includes(t));const unique=[...new Set([...ma.traits,...mb.traits])];const complement=Math.min(100,55+unique.length*6-shared.length*3);document.getElementById('chemResult').innerHTML=`<div class="grid g2"><div><div class="pn">${a.value}</div><div class="role">${ma.role}</div><div class="tags">${ma.traits.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><div><div class="pn">${b.value}</div><div class="role">${mb.role}</div><div class="tags">${mb.traits.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div></div><div class="sec"><div><h2>Role-fit snapshot</h2></div><div class="big">${complement}</div></div><div class="bar"><span style="width:${complement}%"></span></div><div class="grid g2" style="margin-top:14px"><div class="card"><h3>Combined strengths</h3><div class="tags">${unique.map(t=>`<span class="tag">${t}</span>`).join('')}</div></div><div class="card"><h3>Overlap</h3>${shared.length?`<div class="tags">${shared.map(t=>`<span class="tag">${t}</span>`).join('')}</div>`:'<p>Little direct archetype overlap, which can improve role clarity.</p>'}</div></div><p><small>Fit score is a simple archetype-balance indicator, not a claim about actual on-court record.</small></p>`}
const traitGroups={creation:['creation','playmaking','passing','organization','shot creation','secondary creation','secondary playmaking'],shooting:['shooting','spacing','shot making','midrange'],rebounding:['rebounding','size','strength'],defense:['defense','rim protection','perimeter defense','point of attack','steals','activity'],rimPressure:['rim pressure','slashing','cutting','transition','physicality']};
function lineup(){return `<section class="hero"><div class="eye">Build a five</div><h1>Lineup Lab</h1><p>Select five players to inspect role balance and identify likely strengths or gaps.</p></section><div class="card"><div class="checkgrid">${P.map(p=>`<label class="player-check"><input type="checkbox" class="lineup-check" value="${p}"> <span><b>${p}</b><br><small>${D.meta[p].role}</small></span></label>`).join('')}</div><div id="lineupResult" style="margin-top:18px"></div></div>`}
function scoreGroup(names,group){const terms=traitGroups[group];return names.reduce((sum,p)=>sum+D.meta[p].traits.filter(t=>terms.includes(t)).length,0)}
function renderLineup(){const checked=[...document.querySelectorAll('.lineup-check:checked')].map(x=>x.value);const out=document.getElementById('lineupResult');if(!out)return;document.querySelectorAll('.lineup-check').forEach(x=>x.disabled=!x.checked&&checked.length>=5);if(checked.length!==5){const left=5-checked.length;out.innerHTML=`<div class="empty">${left>0?`Select ${left} more player${left===1?'':'s'} to analyze the lineup.`:'Select exactly five players.'}</div>`;return}const raw={Creation:scoreGroup(checked,'creation'),Shooting:scoreGroup(checked,'shooting'),Rebounding:scoreGroup(checked,'rebounding'),Defense:scoreGroup(checked,'defense'),'Rim pressure':scoreGroup(checked,'rimPressure')};const scores=Object.fromEntries(Object.entries(raw).map(([k,v])=>[k,Math.min(100,30+v*12)]));const strengths=Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,2).map(x=>x[0]);const gaps=Object.entries(scores).sort((a,b)=>a[1]-b[1]).slice(0,2).map(x=>x[0]);out.innerHTML=`<div class="sec"><div><h2>${checked.join(' · ')}</h2><p>Archetype balance, not a predicted record.</p></div></div><div class="grid g2">${Object.entries(scores).map(([k,v])=>`<div class="card"><div class="lab">${k}</div><div class="big">${v}</div><div class="bar"><span style="width:${v}%"></span></div></div>`).join('')}</div><div class="grid g2" style="margin-top:14px"><div class="card"><h3>Likely strengths</h3><p>${strengths.join(' · ')}</p></div><div class="card"><h3>Potential pressure points</h3><p>${gaps.join(' · ')}</p></div></div>`}
function runCard(r,detail=false,focus=null){const leaderBits=Object.entries(r.leaders).map(([k,v])=>`<div><span>${statLabel[k]}</span><b class="${focus&&v.player===focus?'winner':''}">${v.player} ${v.value}</b></div>`).join('');return `<div class="card ${detail?'':'run-row'}"><div class="run-row-head"><div><div class="pn">Run ${r.run}</div><div class="role">${r.date}</div></div><div class="lab">${r.games} games</div></div><p>${r.location} · ${r.court}${r.format?' · '+r.format:''}</p><div class="run-leaders">${leaderBits}</div></div>`}
function runs(){return `<section class="hero"><div class="eye">Game history</div><h1>Runs</h1><p>Every recorded session through Run ${D.through_run}, with all tracked category leaders.</p></section><div class="note"><b>Game-level box scores are the next data layer.</b> Current source data contains run summaries, not individual game lineups or player box scores.</div><div class="run-grid">${[...D.runs].reverse().map(r=>runCard(r)).join('')}</div>`}
function records(){const career=[['Career points',rank('pts')[0],D.players[rank('pts')[0]].pts],['Career rebounds',rank('reb')[0],D.players[rank('reb')[0]].reb],['Career assists',rank('ast')[0],D.players[rank('ast')[0]].ast],['Career steals',rank('stl')[0],D.players[rank('stl')[0]].stl],['Career blocks',rank('blk')[0],D.players[rank('blk')[0]].blk],['Career wins',rank('wins')[0],D.players[rank('wins')[0]].wins],['PPG',rankBy(x=>x.ppg)[0],n(D.players[rankBy(x=>x.ppg)[0]].ppg)],['RPG',rankBy(x=>x.rpg)[0],n(D.players[rankBy(x=>x.rpg)[0]].rpg)],['APG',rankBy(x=>x.apg)[0],n(D.players[rankBy(x=>x.apg)[0]].apg)],['Win%',rankBy(x=>x.wins/x.gp)[0],pct(D.players[rankBy(x=>x.wins/x.gp)[0]].wins/D.players[rankBy(x=>x.wins/x.gp)[0]].gp)]];const runRecords=Object.keys(statLabel).map(k=>{const best=[...D.runs].sort((a,b)=>b.leaders[k].value-a.leaders[k].value)[0];return [statLabel[k],best.leaders[k].player,best.leaders[k].value,`Run ${best.run}`]});return `<section class="hero"><div class="eye">History book</div><h1>Records</h1><p>Career leaders plus the best recorded single-run category marks.</p></section><div class="sec"><div><h2>Career records</h2></div></div><div class="grid g3">${career.map(([label,p,v])=>`<div class="card click" data-profile="${p}"><div class="lab">${label}</div><div class="big">${v}</div><div class="role">${p}</div></div>`).join('')}</div><div class="sec"><div><h2>Single-run records</h2></div></div><div class="grid g3">${runRecords.map(([label,p,v,run])=>`<div class="card click" data-profile="${p}"><div class="lab">${label}</div><div class="big">${v}</div><div class="role">${p}</div><p>${run}</p></div>`).join('')}</div>`}
function render(){const views={home,leaders,players,compare,chemistry,lineup,runs,records};app.innerHTML=(views[tab]||home)();bind();if(tab==='compare'){const a=document.getElementById('cmpA'),b=document.getElementById('cmpB');b.selectedIndex=Math.min(1,P.length-1);a.onchange=b.onchange=renderComparison;renderComparison()}if(tab==='chemistry'){const a=document.getElementById('chemA'),b=document.getElementById('chemB');b.selectedIndex=Math.min(1,P.length-1);a.onchange=b.onchange=renderChemistry;renderChemistry()}if(tab==='lineup'){document.querySelectorAll('.lineup-check').forEach(x=>x.onchange=renderLineup);renderLineup()}scrollTo(0,0)}
function setTab(next){tab=next;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('on',x.dataset.tab===tab));render()}
function bind(){document.querySelectorAll('[data-profile]').forEach(el=>el.onclick=()=>profile(el.dataset.profile));document.querySelectorAll('[data-tabjump]').forEach(el=>el.onclick=()=>setTab(el.dataset.tabjump))}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
render();