function playerBadges(p){const x=D.players[p],metrics=[['ppg','Scorer'],['rpg','Glass Cleaner'],['apg','Playmaker'],['spg','Pickpocket'],['bpg','Rim Protector'],['pps','Efficient Scorer']];return metrics.map(([k,label])=>({label,score:normMetric(p,k)})).sort((a,b)=>b.score-a.score).slice(0,2).map(x=>x.label)}
function runAwardCount(p){let c=0;D.runs.forEach(r=>Object.values(r.leaders||{}).forEach(v=>{if(v.player===p)c++}));return c}
function recentForm(p){const x=D.players[p],rr=Object.entries(x.runs||{}).sort((a,b)=>Number(a[0])-Number(b[0])).slice(-3).map(([,s])=>s);if(!rr.length)return null;const gp=rr.reduce((a,s)=>a+(s.gp||0),0)||1,pts=rr.reduce((a,s)=>a+(s.pts||0),0),reb=rr.reduce((a,s)=>a+(s.reb||0),0),ast=rr.reduce((a,s)=>a+(s.ast||0),0),fgm=rr.reduce((a,s)=>a+(s.fgm||0),0),fga=rr.reduce((a,s)=>a+(s.fga||0),0),tpm=rr.reduce((a,s)=>a+(s.tpm||0),0),tpa=rr.reduce((a,s)=>a+(s.tpa||0),0);const form={ppg:pts/gp,rpg:reb/gp,apg:ast/gp,fg:fga?fgm/fga:null,tp:tpa?tpm/tpa:null};const delta=(form.ppg-(x.ppg||0))+(form.rpg-(x.rpg||0))*.35+(form.apg-(x.apg||0))*.5;form.label=delta>.65?'Heating Up':delta>.2?'Trending Up':delta>-.3?'Steady':'Finding Rhythm';return form}
function nextMilestone(p,k,step,label){const v=statValue(D.players[p],k),target=Math.ceil((v+1)/step)*step;return {p,k,label,v,target,left:target-v,progress:v/target}}
function milestones(){const all=[];P.forEach(p=>{all.push(nextMilestone(p,'pts',50,'career points'),nextMilestone(p,'reb',50,'career rebounds'),nextMilestone(p,'ast',25,'career assists'),nextMilestone(p,'stl',25,'career steals'),nextMilestone(p,'blk',10,'career blocks'),nextMilestone(p,'tpm',25,'career threes'))});return all.filter(x=>x.left>0).sort((a,b)=>a.left/b.target-b.left/a.target).slice(0,4)}
function milestoneWatch(){return `<div class="milestone-watch">${milestones().map(m=>`<div class="milestone-watch-item"><div><b>${playerLink(m.p)}</b><span>${m.target} ${m.label}</span></div><strong>${m.left} away</strong><div class="recordbar"><span style="width:${Math.min(100,m.progress*100)}%"></span></div></div>`).join('')}</div>`}
function achievedMilestones(){const defs=[['pts',50,'Career Points'],['reb',50,'Career Rebounds'],['ast',25,'Career Assists'],['stl',25,'Career Steals'],['blk',10,'Career Blocks'],['tpm',25,'Career Threes']];const out=[];P.forEach(p=>{const rr=Object.entries(D.players[p].runs||{}).sort((a,b)=>Number(a[0])-Number(b[0]));defs.forEach(([k,step,label])=>{let total=0,next=step;rr.forEach(([rn,s])=>{total+=s[k]||0;while(total>=next){out.push({p,k,label,target:next,run:Number(rn)});next+=step}})})});return out.sort((a,b)=>b.run-a.run||b.target-a.target||a.p.localeCompare(b.p)).slice(0,6)}
function milestoneBoard(){const ms=achievedMilestones();return `<div class="milestone-board">${ms.map(m=>`<div class="card milestone-achieved"><div class="milestone-icon">✓</div><div><div class="kicker">Milestone reached · Run ${m.run}</div><div class="pn">${playerLink(m.p)}</div><div class="milestone-number">${m.target}</div><div class="lab">${m.label}</div></div></div>`).join('')}</div>`}
function formArrow(v,c,epsilon=.05){if(v==null||c==null)return {symbol:'—',cls:'flat'};const diff=v-c;if(Math.abs(diff)<epsilon)return {symbol:'—',cls:'flat'};return diff>0?{symbol:'↑',cls:'up'}:{symbol:'↓',cls:'down'}}
function formMetric(label,v,c,fmt=n,epsilon=.05){const a=formArrow(v,c,epsilon);return `<div class="formmetric"><span class="formmetric-label">${label}</span><div class="formmetric-main"><b>${fmt(v)}</b><i class="trend-arrow ${a.cls}">${a.symbol}</i></div><small>Career ${fmt(c)}</small></div>`}
function formCard(p){const f=recentForm(p),x=D.players[p];if(!f)return '';return `<div class="card formcard"><div class="formtop"><div><div class="pn">${playerLink(p)}</div><div class="role">${D.meta[p].role}</div></div><span class="formpill">${f.label}</span></div><div class="formmetrics">${formMetric('PPG',f.ppg,x.ppg,n,.05)}${formMetric('RPG',f.rpg,x.rpg,n,.05)}${formMetric('APG',f.apg,x.apg,n,.05)}${formMetric('3PT%',f.tp,x.tp_pct,pct,.005)}</div></div>`}
function trends(){return `<section class="hero"><div class="eye">Recent form</div><h1>Trends</h1><p>Last-three-run form compared with each player's own career baseline. Every arrow shows whether that stat is currently above, below, or near the player's usual level.</p></section><div class="trendcards">${P.map(formCard).join('')}</div><div class="sec"><div><h2>How to read this</h2><p>↑ = above career baseline · ↓ = below career baseline · — = roughly in line. “Finding Rhythm” only describes the last three runs relative to that player's own history.</p></div></div>`}
function highlights(){return `<section class="hero"><div class="eye">Film room</div><h1>Highlights</h1><p>A home for game clips, standout plays and timestamped moments as the video library grows.</p></section><div class="card highlight-empty"><div class="big">🎬</div><h3>Highlights coming later</h3><p>The tab is ready, but we're keeping it intentionally light until clips and timestamps are organized.</p></div>`}
function headToHead(a,b){let against={gp:0,aw:0,bw:0,margin:0},together={gp:0,w:0,margin:0};D.games.forEach(g=>{const a1=g.team1.includes(a),a2=g.team2.includes(a),b1=g.team1.includes(b),b2=g.team2.includes(b);if((a1&&b2)||(a2&&b1)){against.gp++;const am=a1?g.score1-g.score2:g.score2-g.score1;against.margin+=am;if(am>0)against.aw++;if(am<0)against.bw++}if((a1&&b1)||(a2&&b2)){together.gp++;const m=a1?g.score1-g.score2:g.score2-g.score1;together.margin+=m;if(m>0)together.w++}});return {against,together}}
function compactCompareMetrics(A,B){return [['PPG',A.ppg,B.ppg,2],['RPG',A.rpg,B.rpg,2],['APG',A.apg,B.apg,2],['SPG',A.spg,B.spg,2],['BPG',A.bpg,B.bpg,2],['3P%',A.tp_pct,B.tp_pct,'pct'],['PPS',A.pps,B.pps,3],['Win%',A.win_pct,B.win_pct,'pct']]}
const originalRenderComparison=renderComparison;
renderComparison=function(){const a=document.getElementById('cmpA'),b=document.getElementById('cmpB');if(!a||!b)return;if(a.value===b.value)b.value=P.find(x=>x!==a.value)||a.value;const A=D.players[a.value],B=D.players[b.value],h=headToHead(a.value,b.value),metrics=compactCompareMetrics(A,B);const fmt=(v,f)=>f==='pct'?pct(v):n(v,f);document.getElementById('comparison').innerHTML=`<div class="grid g2 compare-names"><div><div class="pn">${a.value}</div><div class="role">${D.meta[a.value].role}</div></div><div><div class="pn">${b.value}</div><div class="role">${D.meta[b.value].role}</div></div></div><div class="compactmetrics">${metrics.map(([l,av,bv,f])=>`<div class="metric-row"><span class="label">${l}</span><span class="value ${av>bv?'winner':''}">${fmt(av,f)}</span><span class="value ${bv>av?'winner':''}">${fmt(bv,f)}</span></div>`).join('')}</div><div class="compare-insights"><div class="card"><div class="kicker">Against each other</div><div class="big">${h.against.gp}</div><div class="lab">games opposed</div><p>${a.value} ${h.against.aw}–${h.against.bw} ${b.value}${h.against.gp?` · ${a.value} avg margin ${h.against.margin/h.against.gp>=0?'+':''}${n(h.against.margin/h.against.gp,1)}`:''}</p></div><div class="card"><div class="kicker">As teammates</div><div class="big">${h.together.gp}</div><div class="lab">games together</div><p>${h.together.gp?`${h.together.w}–${h.together.gp-h.together.w} · ${pct(h.together.w/h.together.gp)} win rate · ${h.together.margin/h.together.gp>=0?'+':''}${n(h.together.margin/h.together.gp,1)} avg margin`:'No shared-team games recorded.'}</p></div></div>`}
const originalPlayerCard=playerCard;
playerCard=function(p){const m=D.meta[p],title=m.title||m.role;let html=originalPlayerCard(p);html=html.replace(`<div class="role">${m.role}</div><p>${m.position}</p>`,`<div class="signature-title-card">${title}</div><p class="player-position">${m.position}</p>`);return html.replace('<div class="taplabel">',`<div class="badge-row"><span class="badge-label">Badges</span>${playerBadges(p).map(b=>`<span class="playerbadge">${b}</span>`).join('')}</div><div class="taplabel">`)}
const originalProfile=profile;
profile=function(p){originalProfile(p);const x=D.players[p],m=D.meta[p],rr=Object.values(x.runs||{}),gp=x.gp||1,astTo=x.tov?x.ast/x.tov:null,threeRate=x.fga?x.tpa/x.fga:null,shots=x.fga/gp,def=(x.stl+x.blk)/gp,ppgs=rr.map(s=>s.ppg||0),mean=ppgs.reduce((a,b)=>a+b,0)/(ppgs.length||1),variance=ppgs.reduce((a,v)=>a+(v-mean)**2,0)/(ppgs.length||1),sd=Math.sqrt(variance),awards=runAwardCount(p),badges=playerBadges(p),title=m.title||m.role;const heroRole=document.querySelector('.profile-banner .role');if(heroRole){heroRole.textContent=title;heroRole.className='signature-title-profile'}const scoutingHeading=[...document.querySelectorAll('.sec h2')].find(el=>el.textContent.trim()==='Scouting profile');const scoutingCard=scoutingHeading?.closest('.sec')?.nextElementSibling?.querySelector('.card');if(scoutingCard){const h3=scoutingCard.querySelector('h3');if(h3)h3.insertAdjacentHTML('afterend',`<div class="scouting-style"><span>Playing style</span><b>${m.role}</b></div>`)}const banner=document.querySelector('.profile-banner');if(banner)banner.insertAdjacentHTML('afterend',`<div class="profile-identity"><div><span class="identity-label">Player badges</span><div class="badge-row profile-badges">${badges.map(b=>`<span class="playerbadge">${b}</span>`).join('')}</div></div><div class="accolade-chip"><span>Run accolades</span><b>${awards}</b><small>category-leading finishes</small></div></div>`);const html=`<div class="sec"><div><h2>Advanced stats</h2><p>Extra context derived from the recorded box scores. Usage and activity measures are descriptive proxies, not possession-based NBA metrics.</p></div></div><div class="grid g3 advancedgrid"><div class="card"><div class="big">${astTo==null?'—':n(astTo,2)}</div><div class="lab">AST / TOV</div></div><div class="card"><div class="big">${pct(threeRate)}</div><div class="lab">3PA rate</div></div><div class="card"><div class="big">${n(shots,2)}</div><div class="lab">FGA / game · usage proxy</div></div><div class="card"><div class="big">${n(def,2)}</div><div class="lab">STL + BLK / game</div></div><div class="card"><div class="big">${n(sd,2)}</div><div class="lab">PPG run variability</div></div><div class="card accolade-stat"><div class="big">${awards}</div><div class="lab">Run category accolades</div><small>Small career tally of category-leading run finishes.</small></div></div>`;app.insertAdjacentHTML('beforeend',html);bind()}
const originalHome=home;
home=function(){const base=originalHome();const insert=`<div class="sec milestone-heading"><div><div class="eye">Career achievements</div><h2>Milestones</h2><p>Notable career marks reached across the recorded history.</p></div></div>${milestoneBoard()}<div class="sec milestone-watch-heading"><div><h3>Milestone watch</h3><p>Who is closest to the next mark.</p></div></div>${milestoneWatch()}<div class="sec"><div><h2>Recent form</h2><p>A quick look at the latest three runs, compared with each player's own baseline.</p></div><button class="action" data-tabjump="trends">View all trends →</button></div><div class="grid g3 home-form-preview">${P.slice().sort((a,b)=>Math.abs((recentForm(b)?.ppg||0)-D.players[b].ppg)-Math.abs((recentForm(a)?.ppg||0)-D.players[a].ppg)).slice(0,3).map(formCard).join('')}</div>`;return base.replace('<div class="sec"><div><h2>Explore the league</h2>',insert+'<div class="sec"><div><h2>Explore the league</h2>')}
