function teamRating(team){return team.reduce((s,p)=>s+playerRating(p),0)/team.length}
function teamFingerprint(team){return metricKeys.slice(0,6).map(k=>team.reduce((s,p)=>s+normMetric(p,k),0)/team.length)}
function matchupDiff(a,b){const rd=Math.abs(teamRating(a)-teamRating(b));const A=teamFingerprint(a),B=teamFingerprint(b);const shape=A.reduce((s,v,i)=>s+Math.abs(v-B[i]),0)/A.length*100;return rd*.72+shape*.28}
function balanceScore(a,b){return Math.max(0,100-matchupDiff(a,b)*1.6)}
function combinations(arr,k){const out=[];function rec(start,pick){if(pick.length===k){out.push([...pick]);return}for(let i=start;i<=arr.length-(k-pick.length);i++){pick.push(arr[i]);rec(i+1,pick);pick.pop()}}rec(0,[]);return out}
function chooseCandidate(cands,fairness){const sorted=[...cands].sort((a,b)=>a.diff-b.diff),pool=Math.max(1,Math.ceil(sorted.length*(1-fairness/100)*.55));return sorted[Math.floor(Math.random()*pool)]||sorted[0]}
function lineupProfile(team){const rating=teamRating(team);const fp=teamFingerprint(team);const labels=['Scoring','Rebounding','Playmaking','Steals','Rim protection','Efficiency'];return `<div class="lineupnames">${team.map(p=>`<span>${p}</span>`).join('')}</div><div class="big">${n(rating,1)}</div><div class="lab">Stat balance rating</div><div class="profilebars">${fp.map((v,i)=>{const score=Math.round(v*100);return `<div class="profilemetric"><div class="profilemetric-head"><span>${labels[i]}</span><b>${score}</b></div><div class="bar"><i style="width:${score}%"></i></div></div>`}).join('')}</div>`}
function matchupGraphic(a,b){const A=teamFingerprint(a),B=teamFingerprint(b),labels=['Scoring','Rebounding','Playmaking','Steals','Rim protection','Efficiency'];return `<div class="card matchupviz"><div class="kicker">Head-to-head profile</div><h3>Where each team has the edge</h3><div class="matchlegend"><span><i class="teamAkey"></i>Team A / starters</span><span><i class="teamBkey"></i>Team B / opponent</span></div><div class="matchrows">${labels.map((label,i)=>`<div class="matchrow"><span>${label}</span><div class="dualbar"><i class="a" style="width:${Math.round(A[i]*100)}%"></i><i class="b" style="width:${Math.round(B[i]*100)}%"></i></div><b>${Math.round(A[i]*100)}–${Math.round(B[i]*100)}</b></div>`).join('')}</div></div>`}
function lineup(){return `<section class="hero"><div class="eye">Team builder</div><h1>Lineup Lab</h1><p>Lock in two to five teammates and let the lab complete your five plus a fair opponent, or select ten players and split them into a balanced 5v5.</p></section><div class="tabswitch"><button class="subtab on" data-lineup-mode="starter">Build around 2–5 players</button><button class="subtab" data-lineup-mode="split">Fair random 5v5</button></div><div id="lineupMode"></div>`}
function lineupChecks(cls,max,help=`Select exactly ${max} players.`){return `<div class="checkgrid">${P.map(p=>`<label class="player-check"><input type="checkbox" class="${cls}" value="${p}"> <span><b>${p}</b><br><small>${D.meta[p].role}</small></span></label>`).join('')}</div><small>${help}</small>`}
function fairnessControl(id='fairness'){return `<div class="faircontrol"><div><b>Fairness preference</b><p>Higher = closest statistical balance. Lower = more variation when reshuffling.</p></div><div class="sliderrow"><input id="${id}" type="range" min="0" max="100" value="85"><b id="${id}Label">85</b></div></div>`}
function renderLineupMode(mode='starter'){document.querySelectorAll('.subtab').forEach(b=>b.classList.toggle('on',b.dataset.lineupMode===mode));const host=document.getElementById('lineupMode');if(!host)return;if(mode==='starter'){host.innerHTML=`<div class="card"><div class="kicker">Locked core</div><h3>Pick 2–5 players you want together</h3><p>The generator will keep every selected player on Team A, fill any open spots, then build the fairest available opponent.</p>${lineupChecks('starter-check',5,'Select at least 2 and at most 5 locked players.')} ${fairnessControl('starterFair')}<div class="toolbar"><button class="action" id="findOpponent">Build teams</button><button class="action ghost" id="reshuffleOpponent">Reshuffle</button></div><div id="starterResult" style="margin-top:16px"></div></div>`;bindStarter()}else{host.innerHTML=`<div class="card">${lineupChecks('split-check',10)}${fairnessControl('splitFair')}<div class="toolbar"><button class="action" id="makeTeams">Create fair teams</button><button class="action ghost" id="reshuffleTeams">Reshuffle</button></div><div id="splitResult" style="margin-top:16px"></div></div>`;bindSplit()}}
function selected(cls){return [...document.querySelectorAll('.'+cls+':checked')].map(x=>x.value)}
function capChecks(cls,max){const vals=selected(cls);document.querySelectorAll('.'+cls).forEach(x=>x.disabled=!x.checked&&vals.length>=max);return vals}
function partialLineupCandidates(locked){const need=5-locked.length,available=P.filter(p=>!locked.includes(p)),fills=combinations(available,need),out=[];fills.forEach(fill=>{const team=[...locked,...fill],remaining=P.filter(p=>!team.includes(p));combinations(remaining,5).forEach(opp=>out.push({team,opp,diff:matchupDiff(team,opp)}))});return out}
function findOpponent(reshuffle=false){const locked=selected('starter-check'),out=document.getElementById('starterResult');if(locked.length<2||locked.length>5){out.innerHTML=`<div class="empty">Select between two and five players you want locked together.</div>`;return}const cands=partialLineupCandidates(locked),fair=Number(document.getElementById('starterFair').value),pick=chooseCandidate(cands,fair);if(!pick){out.innerHTML=`<div class="empty">There are not enough available players to build this matchup.</div>`;return}const added=pick.team.filter(p=>!locked.includes(p));out.innerHTML=`<div class="note" style="margin-bottom:14px"><b>Locked together:</b> ${locked.join(' · ')}${added.length?`<br><small>Added to complete the five: ${added.join(' · ')}</small>`:'<br><small>You selected the full starting five.</small>'}</div><div class="matchup"><div class="card teamcard"><div class="kicker">Completed Team A</div>${lineupProfile(pick.team)}</div><div class="matchcenter"><div class="balancebadge">${n(balanceScore(pick.team,pick.opp),0)}</div><div class="lab">Balance score / 100</div><p>${fair>=80?'Tight balance target':fair>=45?'Moderate variation':'High variation'}.</p></div><div class="card teamcard"><div class="kicker">Suggested opponent</div>${lineupProfile(pick.opp)}</div></div>${matchupGraphic(pick.team,pick.opp)}<p><small>Your selected players always stay together. Any open Team A spots and the opposing five are chosen from the remaining pool using recorded production, efficiency and win rate. This is a team-making aid, not a predicted game result.</small></p>`}
function splitTeams(){const pool=selected('split-check'),out=document.getElementById('splitResult');if(pool.length!==10){out.innerHTML=`<div class="empty">Select exactly ten players first.</div>`;return}const first=pool[0],cands=combinations(pool.slice(1),4).map(rest=>{const A=[first,...rest],B=pool.filter(p=>!A.includes(p));return {A,B,diff:matchupDiff(A,B)}}),fair=Number(document.getElementById('splitFair').value),pick=chooseCandidate(cands,fair);out.innerHTML=`<div class="matchup"><div class="card teamcard"><div class="kicker">Team A</div>${lineupProfile(pick.A)}</div><div class="matchcenter"><div class="balancebadge">${n(balanceScore(pick.A,pick.B),0)}</div><div class="lab">Balance score / 100</div><p>Move the fairness slider lower for more lineup variety.</p></div><div class="card teamcard"><div class="kicker">Team B</div>${lineupProfile(pick.B)}</div></div>${matchupGraphic(pick.A,pick.B)}`}
function bindStarter(){document.querySelectorAll('.starter-check').forEach(x=>x.onchange=()=>capChecks('starter-check',5));const s=document.getElementById('starterFair');s.oninput=()=>document.getElementById('starterFairLabel').textContent=s.value;document.getElementById('findOpponent').onclick=()=>findOpponent(false);document.getElementById('reshuffleOpponent').onclick=()=>findOpponent(true)}
function bindSplit(){document.querySelectorAll('.split-check').forEach(x=>x.onchange=()=>capChecks('split-check',10));const s=document.getElementById('splitFair');s.oninput=()=>document.getElementById('splitFairLabel').textContent=s.value;document.getElementById('makeTeams').onclick=splitTeams;document.getElementById('reshuffleTeams').onclick=splitTeams}
